### ISSUE TITLE
Bug in mesh 0.5.0

### ISSUE THREAD

**Issue by andriy-zhelvachenko** [senecajs/seneca-mesh#10]
The code below works with 0.4.0 and fails with 0.5.0

1) Run base
2) Run subcsriber1
3) Run subscriber2
4) Run publisher

**Comment by andriy-zhelvachenko** [comment]
#!/opt/local/bin/node

// start base seneca node 
require('seneca')()
  .use('mesh', {base:true});

**Comment by andriy-zhelvachenko** [comment]
#!/opt/local/bin/node

require('seneca')()
  .use('mesh', {auto:true, listen:[ {pins:['ns:mmmmm,what:aaaaaaaa,cmd:updates','ns:mmmmm,what:aaaaaaaa,cmd:publish'], model:'publish'}]})
  .ready(function(){
    var s = this;
    s.add('ns:mmmmm,cmd:updates,what:aaaaaaaa', function(msg, done){
      console.log('Subscriber1|Updates|Message: ' + JSON.stringify(msg));
      done(null, {status:'ok', src:'subcriber1'});
    });
    s.add('ns:mmmmm,cmd:publish,what:aaaaaaaa', function(msg, done){
      console.log('Subscriber1|Publish|Message: ' + JSON.stringify(msg));
      done(null, {status:'accepted', src:'subcriber1'});
    });
  });

**Comment by andriy-zhelvachenko** [comment]
#!/opt/local/bin/node

require('seneca')()
  .use('mesh', {auto:true, listen:[ {pins:['ns:mmmmm,what:aaaaaaaa,cmd:updates', 'ns:mmmmm,what:aaaaaaaa,cmd:publish'], model:'publish'}]})
  .ready(function(){
    var s = this;
    s.add('ns:mmmmm,cmd:updates,what:aaaaaaaa', function(msg, done){
      console.log('Subscriber2|Updates|Message: ' + JSON.stringify(msg));
      done(null, {status:'ok', src:'subcriber2'});
    });
    s.add('ns:mmmmm,cmd:publish,what:aaaaaaaa', function(msg, done){
      console.log('Subscriber2|Publish|Message: ' + JSON.stringify(msg));
      done(null, {status:'accepted', src:'subcriber2'});
    });
  });

**Comment by andriy-zhelvachenko** [comment]
#!/opt/local/bin/node

require('seneca')()
  .use('mesh', {auto:true})
  .ready(function(){
    var s = this;
      s.act('ns:mmmmm,cmd:updates,what:aaaaaaaa', {data:'xxx'}, function(error, resp){
        console.log('Publisher|Error: ' + JSON.stringify(error));
        console.log('Publisher|Data: ' + JSON.stringify(resp));
      });
  });

**Comment by rjrodger** [comment]
Investigating...

**Comment by rjrodger** [comment]
this is fixed now - see #11
