### ISSUE TITLE
Root cause for "Maximum stack size exceeded" error

### ISSUE THREAD

**Issue by andriy-zhelvachenko** [senecajs/seneca-mesh#11]
If different mesh processes use semantically same, but alphabetically different pins then it fails with "Max call stack size exceeded" error

i.e. if 2 processes both have
{auto:true, listen:[{pins:['ns:m,what:a,cmd:u'], model:'publish'}]}
this works

if 1 process has
{auto:true, listen:[{pins:['ns:m,what:a,cmd:u'], model:'publish'}]}
and another one has 
{auto:true, listen:[{pins:['ns:m,cmd:u,what:a'], model:'publish'}]}
It fails with the error above!!!

**Comment by andriy-zhelvachenko** [comment]
See details here
https://github.com/senecajs/seneca/issues/336

**Comment by rjrodger** [comment]
these are the same patterns, so it will loop - order of properties is not significant

**Comment by andriy-zhelvachenko** [comment]
Well, i have just double-checked my tests.

While it should work (i.e. loop), in reality it fails with "Maximum call stack size exceeded"

**Comment by rjrodger** [comment]
ok, then it's a bug for sure - could I ask you to create a minimal code example - that would really help to debug? thanks :)

**Comment by andriy-zhelvachenko** [comment]
here is the example
https://gist.github.com/andriy-zhelvachenko/316950a7c112a599e9e9

**Comment by rjrodger** [comment]
Thank You! Investigating...

**Comment by alansikora** [comment]
I'm having a simular issue, quite random. Only one service, and one client. Sometimes I get that error, still could not make mesh reliable.

**Comment by rjrodger** [comment]
OK. Fixed! This issue was due to incorrect canonicalisation of the pins leading to incorrect hash keys. Test case and fix in commit https://github.com/senecajs/seneca-mesh/commit/c2d80479e4fe4de5fe915b8e055355e996d24982

nearly there with the next version!

@andriy-zhelvachenko Thank you so much - this was an important bug to find and fix
