### ISSUE TITLE
Heroku Deployment Support 

### ISSUE THREAD

**Issue by Mohamed-Habshey** [senecajs/seneca-mesh#39]
Hi Everyone,

i need to deploy my services to multiple heroku apps and allow them to connect together using a base service with specific port on heroku.

for ex. i have (mesh-base) app that acts as a base node 

``` javascript
var seneca = require('seneca')({
  timeout: 30000,
  tag: 'base node',
})
.use('mesh',
  {
     port: process.env.PORT || 39999,
        isbase: true,
  });
```

as it might seems i can't bind the mesh-base to **external port** on heroku so other instances can reach it
even i can't route the external port 80 to the internal port allowed by heroku(process.env.PORT).
do i miss something ?
any help will be appreciated?
Regards

**Comment by seonixx** [comment]
Did you get a solution to this?

**Comment by Mohamed-Habshey** [comment]
Hi @seonixx  
well it turns out that heroku doesn't support dyno to dyno http communication.

so i think seneca-mesh won't fit into heroku however i used another transport using redis, 
[seneca-redis-pubsub-transport](https://github.com/senecajs/seneca-redis-pubsub-transport) 
and it works fine. 🙂 

hope it helps.
Regards

**Comment by rjrodger** [comment]
Yeah - seneca-mesh needs a friendly (and flat) network to work - all the nodes needs to be able to communicate with each other over UDP and TCP. Heroku does not seem to provide this as it is a very controlled environment.

@Mohamed-Habshey That's a good workaround
