### ISSUE TITLE
seneca-mesh install fails at node-gyp rebuid

### ISSUE THREAD

**Issue by vishwasvadavi** [senecajs/seneca-mesh#58]
i have the latest build of npm and node.js installed but i get the following error.

> farmhash@1.2.1 install /root/Desktop/node progs/node_modules/farmhash
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: tunneling socket could not be established, cause=connect ETIMEDOUT 92.242.132.27:6050
gyp ERR! stack     at ClientRequest.onError (/usr/local/lib/node_modules/npm/node_modules/request/node_modules/tunnel-agent/index.js:176:17)
gyp ERR! stack     at ClientRequest.g (events.js:260:16)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at Socket.socketErrorListener (_http_client.js:269:9)

npm ERR! farmhash@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the farmhash@1.2.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the farmhash package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild

**Comment by vishwasvadavi** [comment]
No worries.Got it installed in the root directory and it works fine.

**Comment by mmick66** [comment]
Can you please elaborate on that? I am having a similar issue...
