### ISSUE TITLE
Client won't pick up the local service first when I have two base node.

### ISSUE THREAD

**Issue by jie8357IOII** [senecajs/seneca-mesh#65]
I have two base node on two different machine and let them build the same services.
I use the client to connect base1 on machine1 and call the service, I expect the called services will be the local one (mean machine1), but it's machine2.
Did I lost some setting? 

*_## Base1 & service "foo:1" on machine1 *_
```js
require('seneca')()  .add( 'foo:1', function (msg, done) {
done( null, {x:1,v:100+msg.v} )})
 .use('mesh',
  {pin:'foo:1',
   isbase:true,
   host: ip1,
   port: port1,
   bases:[ip2:port2]
  })
```

*_## Base2  & service "foo:1" on machine2 *_
```js
require('seneca')()  .add( 'foo:1', function (msg, done) {
done( null, {x:1,v:100+msg.v} )})
 .use('mesh',
  {pin:'foo:1',
   isbase:true,
   host: ip2,
   port: port2,
   bases:[ip1:port1]
  })
```

**## Client on machine1 "**
```js
require('seneca')()
 .use('mesh', {  host: 'ip1',  bases:[ip1:port1,ip2:port2] })
  .ready( function () {
    var seneca = this
     seneca.act('foo:1,v:2', console.log)
  })
```

**Comment by rjrodger** [comment]
The client will round robin on the two services as both serve the pattern `foo:1` - this is the intended behavior
