### ISSUE TITLE
sample code doesn't work on mac

### ISSUE THREAD

**Issue by cxwcfea** [senecajs/seneca-mesh#67]
I just run the color example from the doc, but it doesn't work.

This is the output from color-service.js:
{"kind":"notice","notice":"hello seneca ymghac9vx8nt/1478268430479/13374/3.2.2/-","level":"info","when":1478268430555}
{"kind":"mesh","bases":["127.0.0.1:39999"],"options":{"isbase":true,"pin":"format:hex","model":"actor","auto":true,"discover":{"defined":{"active":true},"guess":{"active":true},"multicast":{"active":true,"address":null,"max_search":22,"search_interval":111},"registry":{"active":true,"refresh_interval":1111,"prune_first_probability":0.01,"prune_bound":11},"custom":{"active":true},"stop":true},"dumpnet":false,"sneeze":null},"level":"info","actid":"l8tlpr7eic9t/3dnr73hsp2uh","plugin_name":"mesh","pattern":"name:mesh,plugin:define,role:seneca,seq:2,tag:undefined","when":1478268433700}

This is the output from color-client.js:
{"kind":"notice","notice":"hello seneca dylr1bgbpode/1478268441913/13376/3.2.2/-","level":"info","when":1478268441980}
{"kind":"mesh","bases":["127.0.0.1:39999"],"options":{"isbase":false,"model":"actor","auto":true,"discover":{"defined":{"active":true},"guess":{"active":true},"multicast":{"active":true,"address":null,"max_search":22,"search_interval":111},"registry":{"active":true,"refresh_interval":1111,"prune_first_probability":0.01,"prune_bound":11},"custom":{"active":true},"stop":true},"dumpnet":false,"sneeze":null},"level":"info","actid":"q7vs7uhkm7sm/exg0widcdsxj","plugin_name":"mesh","pattern":"name:mesh,plugin:define,role:seneca,seq:2,tag:undefined","when":1478268443034}
{"err":{},"level":"warn","when":1478268443057}
{"notice":"seneca: No matching action pattern found for { format: 'hex', color: 'red' }, and no default result provided (using a default$ property).","code":"act_not_found","err":{"eraro":true,"orig":null,"code":"act_not_found","seneca":true,"package":"seneca","msg":"seneca: No matching action pattern found for { format: 'hex', color: 'red' }, and no default result provided (using a default$ property).","details":{"args":"{ format: 'hex', color: 'red' }","plugin":{}},"callpoint":"at handle_inward_break (/Users/cxwcfea/Myfiles/code/node/micro_services/node_modules/seneca/seneca.js:1155:23)"},"actid":"byqbu4mt5daa/p4m8mygf37fs","msg":{"format":"hex","color":"red","meta$":{"id":"byqbu4mt5daa/p4m8mygf37fs","tx":"p4m8mygf37fs"}},"meta":{},"listen":false,"transport":{},"kind":"act","case":"ERR","duration":786,"level":"error","when":1478268443058}
{"actid":"byqbu4mt5daa/p4m8mygf37fs","msg":{"format":"hex","color":"red","meta$":{"id":"byqbu4mt5daa/p4m8mygf37fs","tx":"p4m8mygf37fs"}},"meta":{},"listen":false,"transport":{},"kind":"act","case":"ERR","info":"seneca: Action undefined callback threw: Cannot read property 'color' of undefined.","code":"act_callback","err":{"eraro":true,"orig":{},"code":"act_callback","seneca":true,"package":"seneca","msg":"seneca: Action undefined callback threw: Cannot read property 'color' of undefined.","details":{"message":"Cannot read property 'color' of undefined","instance":"Seneca/dylr1bgbpode/1478268441913/13376/3.2.2/-","orig$":{},"message$":"Cannot read property 'color' of undefined","plugin":{}},"callpoint":"at Seneca.<anonymous> (/Users/cxwcfea/Myfiles/code/node/micro_services/test.js:6:20)"},"duration":786,"level":"error","when":1478268443061}

MacOS version: 10.12.1
Node version: v5.9.0
seneca version: 3.2.2
seneca-mesh: 0.9.0

**Comment by quiet324** [comment]
Meeting the same issue. Any updates?

**Comment by aaawtest** [comment]
any luck anybody? seems the code wasn't tested on Mac.

**Comment by egorovli** [comment]
See https://github.com/senecajs/seneca-mesh/issues/57, encapsulate the client logic in "ready" event.

**Comment by rjrodger** [comment]
This is fixed
