### ISSUE TITLE
Problem running inside Docker container

### ISSUE THREAD

**Issue by alansikora** [senecajs/seneca-mesh#76]
So, I have a project that uses seneca and seneca-mesh, and I'm having this issue:

```Message: seneca: use-plugin: Could not load plugin mesh defined in seneca-mesh due to error: /usr/src/uPayment-api/node_modules/msgpack/build/Release/msgpackBinding.node: invalid ELF header.```

I understand that an invalid ELF usually means it was built on a different platform, but in this case, I do build inside the container. I even tried cloning during build process and building from sources, no luck.

I also created an issue here: https://github.com/pgriess/node-msgpack/issues/72

Any guesses?

**Comment by alansikora** [comment]
So, my mistake. `.dockerignore` was not correctly set up and was sending one node_modules folder inside... Sorry.

**Comment by chippawah** [comment]
@alansikora Can you explain what you mean by this? I'm running into the same issue as well.

**Comment by chippawah** [comment]
https://github.com/nodezoo/nodezoo-workshop/issues/58 Found the solution here. Indeed the containers need to build their own node_modules for mesh to run in docker.
