### ISSUE TITLE
example in README.md not working

### ISSUE THREAD

**Issue by sbluday** [senecajs/seneca-mesh#78]
I am getting this error

{"err":{},"level":"warn","when":1487183747983}
{"notice":"seneca: No matching action pattern found for { format: 'hex', color: 'red' }, and no default result provided (using a default$ property).","code":"act_not_found","err":{"eraro":true,"orig":null,"code":"act_not_found","seneca":true,"package":"seneca","msg":"seneca: No matching action pattern found for { format: 'hex', color: 'red' }, and no default result provided (using a default$ property).","details":{"args":"{ format: 'hex', color: 'red' }","plugin":{}},"callpoint":"at handle_inward_break (/home/thatisuday/test/seneca-mesh/node_modules/seneca/seneca.js:1178:13)"},"actid":"mklgrn3wj16f/4ow3pvl8pcin","msg":{"format":"hex","color":"red","meta$":{"mi":"mklgrn3wj16f","tx":"4ow3pvl8pcin","id":"mklgrn3wj16f/4ow3pvl8pcin"}},"meta":{},"listen":false,"transport":{},"kind":"act","case":"ERR","duration":955,"level":"error","when":1487183747985}
{"actid":"mklgrn3wj16f/4ow3pvl8pcin","msg":{"format":"hex","color":"red","meta$":{"mi":"mklgrn3wj16f","tx":"4ow3pvl8pcin","id":"mklgrn3wj16f/4ow3pvl8pcin"}},"meta":{},"listen":false,"transport":{},"kind":"act","case":"ERR","info":"seneca: Action undefined callback threw: Cannot read property 'color' of undefined.","code":"act_callback","err":{"eraro":true,"orig":{},"code":"act_callback","seneca":true,"package":"seneca","msg":"seneca: Action undefined callback threw: Cannot read property 'color' of undefined.","details":{"message":"Cannot read property 'color' of undefined","instance":"Seneca/c0k2hge3zu2j/1487183746814/4960/3.3.0/-","orig$":{},"message$":"Cannot read property 'color' of undefined","plugin":{}},"callpoint":"at Seneca.<anonymous> (/home/thatisuday/test/seneca-mesh/color-client.js:14:20)"},"duration":955,"level":"error","when":1487183747987}

**Comment by rjrodger** [comment]
fixed :)
