### ISSUE TITLE
Using 'model: observe' without calling "done" callback throws TIMEOUT error

### ISSUE THREAD

**Issue by jimimatrix** [senecajs/seneca-mesh#85]
Using {model: 'observe'} requires at least one "done" callback to be called otherwise the 'adding' service throws a TIMEOUT (eventually).

This is surprising to me because it was my understanding that {model: observe} is a form of 'fire and forget' strategy for Seneca Mesh/Balance Client.

You can the code reproduction here:
https://github.com/jimimatrix/seneca-mesh-observer-issue

**Comment by rjrodger** [comment]
Thank you - very helpful!

In this case, you need to call `done()` without any arguments - this indicates to Seneca that you have completed your work on the message, even if you have no reply.

You always need to call done, regardless of whether this is a response or not.

BUT: is this a good API design - not sure - you found it surprising, which is not good - I need to think about this!

**Comment by jimimatrix** [comment]
Thanks for getting back to me. Executing a callback signals to me a coupling between sender and receiver. I'm not sure what is happening 'behind the scenes' and whether a sender is actually waiting for a response or whether this is just formality. I'm also not sure if I should be executing the dummy callback before or after running the responding code.

Observe, consume, synchronous, asynchronous. All these terms seem fuzzy in the framework as I try to grock its view of the world.

**Comment by rjrodger** [comment]
Even in the same process, you'd have to call `done()` - it's a signal that you've finish processing the action.

Depending on what you want, you may wish to finish immediately, or only after some processing - hence the `done`.

Terminology: noted!

**Comment by jimimatrix** [comment]
Thanks. `done()` is a signal to whom that the process is finished?

**Comment by rjrodger** [comment]
Seneca itself.

**Comment by jimimatrix** [comment]
While I have you, is there any reason to call `done()` before or after the processing? What is 'waiting' on the `done()` to be executed? If nothing is being passed back, no other process should care when `done()` is called, correct?

**Comment by rjrodger** [comment]
You might still want a timeout on the async operation itself - say you're resizing images and the spawned process fails in some way, or hangs. Then you'll get a time out in the client Seneca process that you can log etc.

**Comment by jimimatrix** [comment]
Got it. Thanks again!
